version: '3.9'
services:
  nuxtjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nuxtjs
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  strapi:
    image: strapi/strapi:alpine
    container_name: ${APP_NAME}-strapi
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ../strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    container_name: ${APP_NAME}-mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ../mongo:/data/db
    networks:
      - backend

networks:
  backend:
